/*
 * Generated by Bluespec Compiler, version 2025.01.1-8-ge9187c10 (build e9187c10)
 * 
 * On Tue Jun 24 12:48:14 IST 2025
 * 
 */

/* Generation options: */
#ifndef __model_mkSpeculaCore_h__
#define __model_mkSpeculaCore_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"

#include "bs_model.h"
#include "mkSpeculaCore.h"

/* Class declaration for a model of mkSpeculaCore */
class MODEL_mkSpeculaCore : public Model {
 
 /* Top-level module instance */
 private:
  MOD_mkSpeculaCore *mkSpeculaCore_instance;
 
 /* Handle to the simulation kernel */
 private:
  tSimStateHdl sim_hdl;
 
 /* Constructor */
 public:
  MODEL_mkSpeculaCore();
 
 /* Functions required by the kernel */
 public:
  void create_model(tSimStateHdl simHdl, bool master);
  void destroy_model();
  void reset_model(bool asserted);
  void get_version(char const **name, char const **build);
  time_t get_creation_time();
  void * get_instance();
  void dump_state();
  void dump_VCD_defs();
  void dump_VCD(tVCDDumpType dt);
};

/* Function for creating a new model */
extern "C" {
  void * new_MODEL_mkSpeculaCore();
}

#endif /* ifndef __model_mkSpeculaCore_h__ */
