/*
 * Generated by Bluespec Compiler, version 2025.01.1-8-ge9187c10 (build e9187c10)
 * 
 * On Tue Jun 24 12:48:14 IST 2025
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkSpeculaCore.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkSpeculaCore::MODEL_mkSpeculaCore()
{
  mkSpeculaCore_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkSpeculaCore()
{
  MODEL_mkSpeculaCore *model = new MODEL_mkSpeculaCore();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkSpeculaCore &INST_top = *((MOD_mkSpeculaCore *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_fetch_and_decode;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_fetch_and_decode;
	 DEF_INST_top_DEF_CAN_FIRE_RL_fetch_and_decode = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_fetch_and_decode = DEF_INST_top_DEF_CAN_FIRE_RL_fetch_and_decode;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_fetch_and_decode)
	   INST_top.RL_fetch_and_decode();
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_pc.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkSpeculaCore::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkSpeculaCore_instance = new MOD_mkSpeculaCore(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkSpeculaCore_instance->set_clk_0)("CLK");
}
void MODEL_mkSpeculaCore::destroy_model()
{
  delete mkSpeculaCore_instance;
  mkSpeculaCore_instance = NULL;
}
void MODEL_mkSpeculaCore::reset_model(bool asserted)
{
  (mkSpeculaCore_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkSpeculaCore::get_instance()
{
  return mkSpeculaCore_instance;
}

/* Fill in version numbers */
void MODEL_mkSpeculaCore::get_version(char const **name, char const **build)
{
  *name = "2025.01.1-8-ge9187c10";
  *build = "e9187c10";
}

/* Get the model creation time */
time_t MODEL_mkSpeculaCore::get_creation_time()
{
  
  /* Tue Jun 24 07:18:14 UTC 2025 */
  return 1750749494llu;
}

/* State dumping function */
void MODEL_mkSpeculaCore::dump_state()
{
  (mkSpeculaCore_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkSpeculaCore & mkSpeculaCore_backing(tSimStateHdl simHdl)
{
  static MOD_mkSpeculaCore *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkSpeculaCore(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkSpeculaCore::dump_VCD_defs()
{
  (mkSpeculaCore_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkSpeculaCore::dump_VCD(tVCDDumpType dt)
{
  (mkSpeculaCore_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkSpeculaCore_backing(sim_hdl));
}
